### ISSUE TITLE
selinux package does not support python < 2.7

### ISSUE THREAD

**Issue by mnarusze** [pycontribs/selinux#41]
I know that this is a corner case but in CentOS 6.10 (still supported till the end of this year or even longer with extended support) python is below 2.7 which means that `site.getsitepackages()` will not work:

```
>>> import site
>>> site.getsitepackages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
```

**Comment by ssbarnea** [comment]
Good luck upgrading it! I have no plans to touch it.   Even CentOS 7 is painful enough to support for the same obsolescence reasons.
