### ISSUE TITLE
Is setuptools really required during runtime?

### ISSUE THREAD

**Issue by dvzrv** [pycontribs/selinux#50]
The [setup.cfg implies that setuptools is required during runtime](https://github.com/pycontribs/selinux/blob/321d66619ed59bec00a9dc6216ce417d7befec41/setup.cfg#L63). Is this really the case?

**Comment by ssbarnea** [comment]
No, feel free to raise a PR to fix it.

**Comment by dvzrv** [comment]
While I have you here, I'm wondering the same about [pip as build-system](https://github.com/pycontribs/selinux/blob/e90f38ea68c578ba0834bb6c2cca119f1d0b0cdb/pyproject.toml#L3).

According to PEP517 you'll probably only need setuptools-scm (git archive is now included) in there. On Arch Linux we recently had to devender a bunch of packages, as they were pulling in pip during build time (for no reason).
