### ISSUE TITLE
Same package name as official selinux python bindings

### ISSUE THREAD

**Issue by tallero** [pycontribs/selinux#52]
Hello,
it seems that this python module installs a `selinux` module just as the official selinux [python bindings](https://github.com/SELinuxProject/selinux), causing package conflicts when using programs which depend on either one of the two.

Can something be done about this?

EDIT: I see from the README one has to install official bindings, so I am wondering, how could that be if this package overwrites them? More in general we have [doubts](https://aur.archlinux.org/packages/libselinux#comment-844678) about how this module works.

**Comment by ssbarnea** [comment]
This package does not override them, it was made like this by design.
