### ISSUE TITLE
support for python 3.7/3.8 dropped

### ISSUE THREAD

**Issue by charltonstanley** [pycontribs/selinux#63]
Hi there,

I noticed that support for python 3.7/3.8 were dropped, however they are both still supported versions of python, according to https://devguide.python.org/versions/. 

3.7 becomes EOL on 2023-06-27, which is ~7 months away.
3.8 becomes EOL on 2024-10, which is ~22 months away.

Any chance we can revert dropping support of python 3.7/3.8 until they are actually unsupported by the python project?

**Comment by charltonstanley** [comment]
@ssbarnea I couldn't help but notice that this issue was unceremoniously closed without as much as a comment as to why python 3.7/3.8 support can't be re-implemented. Being that I don't know why it was dropped, I don't even know if a PR would be accepted to reverse this change, or if the changes simply can't be reversed due to some other dependencies or incompatibilities. Could you at least speak to whether a PR would be accepted to reverse this?

**Comment by sabik** [comment]
@ssbarnea This is affecting me as well.

In addition to the comments by @charltonstanley, I also note that PR #61 doesn't link any issue or other explanation of why support for 3.7 and 3.8 were dropped. Was it causing any problem, or was it incidental to dropping support for EOL versions 3.6 and below?

Python 3.7 and 3.8 are well within their "supported" period, so it's unclear why they'd be dropped?

**Comment by sabik** [comment]
@ssbarnea is there any chance we can have a comment on why python 3.7 and 3.8 support was dropped, please?
